Bump to ELL 0.4
This patch fixes the following error when switching to ELL 0.4:
ell/key.c:39:10: fatal error: key-private.h: No such file or directory
 #include "key-private.h"